server:
  port: 80

spring:
  config:
    import: classpath:config-file/application-db.yml

  application:
    name: toy-backend
  profiles:
    include:
      - db
    active:
      - dev-window
    group:
      dev-window:
        - db-window
      prod:
        - db-prod
