spring:
  config:
    import: classpath:config-file/application-db.yml

  application:
    name: toy-backend
  profiles:
    include:
      - db
    active:
      - dev-window
    group:
      dev-window:
        - db-window
        - dev-port
      prod:
        - db-prod
        - prod-port

--- # 개발 서버 포트
spring:
  config:
    activate:
      on-profile: "dev-port"

server:
  port: 80


--- # prod 서버 포트
spring:
  config:
    activate:
      on-profile: "prod-port"

server:
  port: 8080
